# Nome do workflow de automação
name: CI/CD Pipeline - Tech Challenge

# Definição dos gatilhos (triggers) para execução do pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Definição das tarefas (jobs) que serão executadas
jobs:
  test:
    # Configuração do ambiente virtual do servidor do GitHub
    runs-on: ubuntu-latest

    # Definição dos passos sequenciais da automação
    steps:
      # Passo 1: Download do código do repositório para o servidor virtual
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Instalação e configuração do ambiente Node.js na versão 20
      - name: Configuração do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Passo 3: Instalação das dependências do projeto (Express, pg, Jest, etc.)
      - name: Instalação das dependências
        run: npm install

      # Passo 4: Execução da suíte de testes unitários para validação de cobertura
      - name: Validação da cobertura de testes
        run: npm run test