name: CI/CD Pipeline - Tech Challenge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configuração do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalação das dependências
        run: npm install

      - name: Validação da cobertura de testes
        run: npm run test
